Algoritmo "crescente"


Var

   x, y : real

Inicio

    escreval ("Digite dois numeros: ")
    leia (x)
    leia (y)
    
    enquanto x<>y faca
         se x > y entao
            escreval ("DECRESCENTE")
         senao
              escreval ("CRESCENTE")
         fimse
         
         escreval ("Digite dois numeros: ")
         leia (x)
         leia (y)
    fimenquanto
    
    escreval ("IGUAIS")

Fimalgoritmo